---
title: "Publications"
output: html_document
---


## Published book chapters<br>
- Biogeography, Ecology and Spatial Patterns of Patagonian Lizards. (2020). __Minoli I.__, Pérez C.H.F., Morando M. & Avila L.J., p 189-216 in: Lizards of Patagonia: Diversity, Systematics, Biogeography and Biology of the Reptiles at the End of the World. Eds. Mariana Morando & Luciano Javier Avila. Life Sciences Series, Springer International Publishing AG, Gewerbestrasse 11, 6330 Cham, Switzerland. doi: https://doi.org/10.1007/978-3-030-42752-8_8<br>
<br>
- Conservation concerns about the southernmost lizards of the World. (2020). Kacoliris F.P, __Minoli I.__, Kass C., & Di Pietro D.O., p 407-422 in: Lizards of Patagonia: Diversity, Systematics, Biogeography and Biology of the Reptiles at the End of the World. Eds. Mariana Morando & Luciano Javier Avila. Life Sciences Series, Springer International Publishing AG, Gewerbestrasse 11, 6330 Cham, Switzerland. doi: https://doi.org/10.1007/978-3-030-42752-8_14<br>
<br>
- Diversification and evolutionary histories of Patagonian steppe lizards (2020). Morando M., Medina C.D., __Minoli, I.__, Pérez C.H.F., Sites Jr, J.W. & Avila L.J., p 217-254 in: Lizards of Patagonia: Diversity, Systematics, Biogeography and Biology of the Reptiles at the End of the World. Eds. Mariana Morando & Luciano Javier Avila. Life Sciences Series, Springer International Publishing AG, Gewerbestrasse 11, 6330 Cham, Switzerland. doi: https://doi.org/10.1007/978-3-030-42752-8_9<br>
<br>

## Some of my top published research papers (from 26)<br>
- Velazco, SJE, Rose, MB, de Andrade, JFA,  __Minoli, I__, Franklin, J (2022) flexsdm: An R package for supporting a comprehensive and flexible species distribution modeling workflow. Methods in Ecology and Evolution, early view. doi: https://doi.org/10.1111/2041-210X.13874<br>
<br>
- __Minoli, I__, Cacciali, P, Morando, M & Avila, LJ (2019) Predicting spatial and temporal effects of climate change on the South American lizard genus <i>Teius</i> (Squamata: Teiidae). Amphibia-Reptilia, 40: 313–326. doi: https://doi.org/10.1163/15685381-20181070<br>
<br>
- Avila LJ, Pérez CHF, __Minoli I__, Medina CD, Sites Jr. JW, Morando M (2017) New species of <i>Liolaemus</i> (Reptilia: Squamata) of the <i>Liolaemus donosobarrosi</i> clade (Squamata, Liolaemini) from northwestern patagonia, Neuquén Province, Argentina. Zootaxa 4362, 535–563. doi: http://dx.doi.org/10.11646/zootaxa.4362.4.4<br>
<br>
- __Minoli I__, Avila LJ (2017) Assessing habitat use, effects of future climate change and conservation areas in two <i>Pristidactylus</i> lizards from Argentina. Zootaxa 4237: 91-111. doi: http://dx.doi.org/10.11646/zootaxa.4237.1.5<br>
<br>
- __Minoli I__, Morando M, Avila LJ (2016) Sexual dimorphism and interspecific head variation in <i>Liolaemus melanops</i> complex (Squamata: Liolaemini) based on geometric morphometrics. The Herpetological Journal 26: 225-237. link: https://is.gd/WciYbQ<br>
<br>
- González Marín A, Pérez CHF, __Minoli I__,  Mariana Morando & Luciano Javier Avila (2016) A new lizard species of the <i>Phymaturus</i> patagonicus group (Squamata: Liolaemini) from northern Patagonia, Neuquén, Argentina. Zootaxa 4121: 412–430. doi: https://doi.org/10.11646/zootaxa.4121.4.3<br>
<br>
- Escudero PC, __Minoli I__, González Marín MA, Morando M, Avila LJ (2016) Melanism and ontogeny: a study case in lizards of the <i>Liolaemus fitzingerii</i> group (Squamata: Liolaemini). Canadian Journal of Zoology 94: 199–206. doi: https://doi.org/10.1139/cjz-2015-0112<br>
<br>
- __Minoli I__, Morando M, Avila LJ (2015) Reptiles of Chubut province, Argentina: richness, diversity, conservation status and geographic distribution maps. ZooKeys 498: 103–126. doi: https://doi.org/10.3897/zookeys.498.7476<br>
<br>
- __Minoli I__, Morando M, Avila LJ (2014) Integrative taxonomy in the <i>Liolaemus fitzingerii</i> complex (Squamata: Liolaemini) based on morphological analyses and niche modeling. Zootaxa 3856: 501–528. doi: https://doi.org/10.11646/zootaxa.3856.4.3<br>
<br>
- Avila LJ, Pérez CHF, __Minoli I__, Morando M (2014) A new lizard of the <i>Phymaturus</i> genus (Squamata: Liolaemidae) from Sierra Grande, northeastern Patagonia, Argentina. Zootaxa 3793: 99–118. doi: https://doi.org/10.11646/zootaxa.3793.1.4<br>
<br>
- Avila LJ, Pérez CH., Minoli I, Morando M (2012) A new species of <i>Homonota</i> (Reptilia: Squamata: Gekkota: Phyllodactylidae) from the Ventania mountain range, Southeastern Pampas, Buenos Aires Province, Argentina. Zootaxa 3431: 19–36. doi: https://doi.org/10.11646/zootaxa.3431.1.2<br>
<br>    

## Some of my technical reports (from 6)<br>
- 2020 “BC AR Biodiversity baseline study” Informe 1 - Etapa 1. Technical Report for Massalin Particulares S.R.L. Ariel Insaurralde, Diego Varela, Gustavo Zurita, Elena Gangenova, Juan Pablo Zurano e __Ignacio Minoli__.<br>
<br>
- 2020 to 2021 “Áreas Claves para la Conservación de la Biodiversidad en la Provincia de Corrientes”. Andrés Bosso, Gustavo Zurita, Adrián Di Giacomo, Juan Pablo Zurano, __Ignacio Minoli__, Ariel Insaurralde, Elena Gangenova, Sebastián Cirignoli, Alejandro Giraudo, Agustín Solari, Rubén Delacassa, Guillermo Gil, Gustavo Marino, Rocío Lapido, Diego Varela, Rodrigo Fariña, Delfina Ackerman.<br>
<br>
- 2020 to 2021 “Identificación de Vacíos de Conservación Ecorregionales”. Jesica María Murray, Silvia Inés Quinzio, Marissa Fabrezi, Carlos Luis Bianchi, Gustavo Andrés Zurita, Juan Pablo Zurano, __Ignacio Minoli__, Juan Ariel Insaurralde, Sebastián Cirignoli, Diego Varela, Félix Ignacio Contreras, Adrián Santiago Di Giacomo, Alejandro R. Giraudo, Viviana Solís Neffa, Gisela Mariel Via do Pico, Roberto Manuel Salas, Walter Adrián Medina, Pablo Aceñolaza, Antonio Esteban Frutos, Adriana Silvina Manzano, Carlos I. Piña, Melina Soledad Simoncini, Walter Fabian Sione, Pablo Eugenio Villagra, Bertilde Elda Rossi, Sergio Roig Juñent, Rodolfo Carrara, Valeria Elizabeth Corbalán, Ricardo Jorge Casaux, Valeria Falabella, Maricel Del Luján Giaccardi, María Inés García Betoño, Thais Ham.<br>